import Link from 'next/link';
import React from 'react';
import 'tailwindcss/tailwind.css';

const WhatIsTax = () => {
    return (
        <div className="w-full h-full bg-gray-100 text-black">
            <div className="w-full h-full bg-white p-8 rounded-lg shadow-lg">
                <h1 className="text-4xl font-bold mb-6 text-center">What is Tax?</h1>
                <p className="text-lg mb-4">
                    Tax is a mandatory financial charge or some other type of levy imposed upon a taxpayer by a governmental organization in order to fund government spending and various public expenditures. Failure to pay, along with evasion of or resistance to taxation, is punishable by law.
                </p>
                <h2 className="text-2xl font-semibold mb-4">Types of Taxes</h2>
                <ul className="list-disc list-inside space-y-2">
                    <li>
                        <strong>Income Tax:</strong> A tax that governments impose on income generated by businesses and individuals within their jurisdiction.
                    </li>
                    <li>
                        <strong>Corporate Tax:</strong> A tax imposed on the net income of the company.
                    </li>
                    <li>
                        <strong>Sales Tax:</strong> A tax paid to a governing body for the sales of certain goods and services.
                    </li>
                    <li>
                        <strong>Property Tax:</strong> A tax assessed on real estate by the local government.
                    </li>
                    <li>
                        <strong>Estate Tax:</strong> A tax levied on an heir's inherited portion of an estate if the value of the estate exceeds an exclusion limit set by law.
                    </li>
                </ul>
                <h2 className="text-2xl font-semibold mb-4">Direct and Indirect Taxes</h2>
                <p className="text-lg mb-4">
                    <strong>Direct Tax:</strong> A type of tax that is paid directly by an individual or organization to the imposing entity. Examples include income tax, corporate tax, and property tax.
                </p>
                <p className="text-lg mb-4">
                    <strong>Indirect Tax:</strong> A type of tax that is collected by an intermediary (such as a retailer) from the person who bears the ultimate economic burden of the tax (such as the consumer). Examples include sales tax, value-added tax (VAT), and excise duty.
                </p>
                <h2 className="text-2xl font-semibold mb-4">Difference between Direct and Indirect Taxes</h2>
                <table className="min-w-full bg-white">
                    <thead>
                        <tr>
                            <th className="py-2 px-4 border-b-2 border-gray-300">Criteria</th>
                            <th className="py-2 px-4 border-b-2 border-gray-300">Direct Tax</th>
                            <th className="py-2 px-4 border-b-2 border-gray-300">Indirect Tax</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td className="py-2 px-4 border-b border-gray-300">Definition</td>
                            <td className="py-2 px-4 border-b border-gray-300">Paid directly by an individual or organization to the government.</td>
                            <td className="py-2 px-4 border-b border-gray-300">Collected by an intermediary from the consumer.</td>
                        </tr>
                        <tr>
                            <td className="py-2 px-4 border-b border-gray-300">Examples</td>
                            <td className="py-2 px-4 border-b border-gray-300">Income tax, corporate tax, property tax.</td>
                            <td className="py-2 px-4 border-b border-gray-300">Sales tax, VAT, excise duty.</td>
                        </tr>
                        <tr>
                            <td className="py-2 px-4 border-b border-gray-300">Burden</td>
                            <td className="py-2 px-4 border-b border-gray-300">Borne by the taxpayer.</td>
                            <td className="py-2 px-4 border-b border-gray-300">Passed on to the consumer.</td>
                        </tr>
                        <tr>
                            <td className="py-2 px-4 border-b border-gray-300">Administration</td>
                            <td className="py-2 px-4 border-b border-gray-300">More complex and costly to administer.</td>
                            <td className="py-2 px-4 border-b border-gray-300">Easier and less costly to administer.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <Link href="/" className="bg-white text-black flex justify-center font-serif text-2xl p-4 border-dashed	border-2 border-red-900">Back To Home</Link>
        </div>
        
    );
};

export default WhatIsTax;
